name: Publish Package

on: workflow_dispatch

jobs:
  publish:
    strategy:
      matrix:
        package: ["hubbado-trailblazer"]

    uses: hubbado/workflows/.github/workflows/component-package.yml@main
    with:
      package: ${{ matrix.package }}
    secrets:
      PUBLISH_PACKAGE_WORKFLOW: ${{ secrets.PUBLISH_PACKAGE_WORKFLOW }}
